openapi: 3.1.0
x-stoplight:
  id: 2300b1a6d0c75
info:
  version: 0.1.0
  title: Device API
  summary: Effective Range device API
  description: Edge device API for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
tags:
  - name: device
    description: Edge device
  - name: health
    description: Component health
paths:
  '/device/reserve/{sessionId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: sessionId
        in: path
        required: true
        description: Session ID
    post:
      summary: Reserve device
      tags:
        - device
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: w4ychh28buda2
      operationId: reserve-device
      x-stoplight:
        id: 271yacc6702a5
      description: Reserve device for session
  '/device/release/{sessionId}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: sessionId
        in: path
        required: true
        description: Session ID
    post:
      summary: Release device
      tags:
        - device
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: w4ychh28buda2
      operationId: release-device
      x-stoplight:
        id: gbagx4n5bk3ah
      description: Release device from session
  '/device/activate/{sessionId}':
    post:
      summary: Activate device
      tags:
        - device
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: w4ychh28buda2
      operationId: activate-device
      x-stoplight:
        id: aq16emkx2iucl
      description: Activate device for launch
      requestBody:
        content:
          application/json:
            schema:
              type: array
              x-stoplight:
                id: t5s8hdt03rj88
              items:
                type: object
                $ref: ./model.yaml#/components/schemas/Token
                x-stoplight:
                  id: gftvtlg0p4iq9
    parameters:
      - schema:
          type: string
          format: uuid
        name: sessionId
        in: path
        required: true
        description: Session ID
  '/device/deactivate/{sessionId}':
    post:
      summary: Deactivate device
      tags:
        - device
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: w4ychh28buda2
      operationId: deactivate-device
      x-stoplight:
        id: 5qetcgo65ggdi
      description: Deactivate device for launch
    parameters:
      - schema:
          type: string
          format: uuid
        name: sessionId
        in: path
        required: true
        description: Session ID
  /health/alive:
    $ref: ./health.yaml#/paths/~1health~1alive
  /health/status:
    $ref: ./health.yaml#/paths/~1health~1status
