openapi: 3.1.0
x-stoplight:
  id: dd066f2eb3b6f
info:
  version: 0.1.0
  title: Server API
  summary: Effective Range server API
  description: Backend server API for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
tags:
  - name: device
    description: Edge device
  - name: discipline
    description: Shooting discipline
  - name: range
    description: Shooting range
  - name: session
    description: Shooting session
  - name: shooter
    description: Shooting competitor
paths:
  /discipline:
    post:
      summary: Add discipline
      tags:
        - discipline
      responses:
        '201':
          description: Created
      operationId: add-discipline
      x-stoplight:
        id: a4qjcud5e3muc
      description: Add a clay shooting discipline
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./effective-range-model.yaml#/components/schemas/Discipline
              x-stoplight:
                id: oesbgk7s2r9bw
    get:
      summary: Get disciplines
      tags:
        - discipline
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: ./effective-range-model.yaml#/components/schemas/Discipline
                  x-stoplight:
                    id: oesbgk7s2r9bw
      operationId: get-disciplines
      x-stoplight:
        id: r023imxkusoo8
      description: Get all clay shooting disciplines
  '/discipline/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Discipline ID
    get:
      summary: Get discipline
      tags:
        - discipline
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Discipline
                x-stoplight:
                  id: oesbgk7s2r9bw
      operationId: get-discipline
      x-stoplight:
        id: t86q0egkjz12p
      description: Get a discipline by ID
      parameters: []
  /shooter:
    get:
      summary: Get shooters
      tags:
        - shooter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: ./effective-range-model.yaml#/components/schemas/Shooter
                  x-stoplight:
                    id: 0adx94x6y33pf
      operationId: get-shooters
      x-stoplight:
        id: 8019pvexup91b
      description: Get all shooter
    post:
      summary: Add shooter
      tags:
        - shooter
      responses:
        '201':
          description: Created
      operationId: add-shooter
      x-stoplight:
        id: tzsibxbelfecv
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./effective-range-model.yaml#/components/schemas/Shooter
              x-stoplight:
                id: 0adx94x6y33pf
      description: Add new shooter
  '/shooter/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Shooter ID
    get:
      summary: Get shooter
      tags:
        - shooter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Shooter
                x-stoplight:
                  id: 0adx94x6y33pf
      operationId: get-shooter
      x-stoplight:
        id: 26nf97y2c8xq6
      description: Get shooter by ID
  /device:
    get:
      responses:
        '200':
          description: Returned devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: ./effective-range-model.yaml#/components/schemas/Device
                  x-stoplight:
                    id: g4ecd4xr0576j
      operationId: get-devices
      summary: Get devices
      description: Get a list of all devices
      tags:
        - device
      x-stoplight:
        id: wnwpyt955cft9
    parameters: []
    post:
      summary: Add device
      tags:
        - device
      responses:
        '201':
          description: Added
      operationId: add-device
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./effective-range-model.yaml#/components/schemas/Device
              x-stoplight:
                id: g4ecd4xr0576j
      description: Add a new device
      x-stoplight:
        id: 9ywyj7yupczbl
  /device/active:
    get:
      responses:
        '200':
          description: Returned active devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: ./effective-range-model.yaml#/components/schemas/Device
                  x-stoplight:
                    id: g4ecd4xr0576j
      operationId: get-active-devices
      summary: Get active devices
      description: Get a list of currently active devices
      tags:
        - device
      x-stoplight:
        id: y7v3mgosrqpgi
    parameters: []
  '/device/{id}':
    get:
      responses:
        '200':
          description: Returned device
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Device
                x-stoplight:
                  id: g4ecd4xr0576j
      operationId: get-device
      summary: Get device
      description: Get a device by ID
      tags:
        - device
      x-stoplight:
        id: opzgga0xi0rij
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Device ID
  '/device/{id}/alive':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Device ID
    post:
      summary: Signal device is alive
      tags:
        - device
      responses:
        '202':
          description: Accepted
      operationId: signal-alive
      x-stoplight:
        id: rbbqxxngx6ow3
      description: Device notifies the server it is alive on the network
  '/device/{id}/healthy':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Device ID
    post:
      summary: Signal device is healthy
      tags:
        - device
      responses:
        '202':
          description: Accepted
      operationId: signal-healthy
      x-stoplight:
        id: q1fsh6mzm5qhl
      description: Device notifies the server it is healthy as a heartbeat signal
  /range:
    get:
      summary: Get ranges
      tags:
        - range
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: ./effective-range-model.yaml#/components/schemas/Range
                  x-stoplight:
                    id: ff7hbgjrk72az
      operationId: get-ranges
      description: Get all shooting ranges
      x-stoplight:
        id: qp0mo370uisly
    post:
      summary: Add range
      tags:
        - range
      responses:
        '201':
          description: Added
      operationId: add-range
      description: Add a shooting range
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: ./effective-range-model.yaml#/components/schemas/Range
              x-stoplight:
                id: ff7hbgjrk72az
      x-stoplight:
        id: az16ukej4mtq7
  '/range/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Range ID
    get:
      summary: Get range
      tags:
        - range
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Range
                x-stoplight:
                  id: ff7hbgjrk72az
      operationId: get-range
      description: Get a shooting range by ID
      x-stoplight:
        id: 3y4qn3jj2ejld
  '/range/{id}/session':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Range ID
    get:
      summary: Get active session
      tags:
        - range
        - session
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Session
                x-stoplight:
                  id: mtflbe6ai8ijr
      operationId: get-active-session
      description: Get the active shooting session on a shooting range
      x-stoplight:
        id: mem7mam2niwym
  /session:
    get:
      summary: Get sessions
      tags:
        - session
      responses:
        '200':
          description: Returned sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: ./effective-range-model.yaml#/components/schemas/Session
                  x-stoplight:
                    id: mtflbe6ai8ijr
      operationId: get-sessions
      description: Get all shooting sessions
      x-stoplight:
        id: 80mdoy32p2ncz
    post:
      operationId: create-session
      summary: Create session
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Session
                x-stoplight:
                  id: mtflbe6ai8ijr
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/CreateSessionRequest'
      tags:
        - session
      description: Create a new shooting session on a shooting range
      x-stoplight:
        id: lj3bw804vmomt
  '/session/{id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    get:
      summary: Get session
      tags:
        - session
      responses:
        '200':
          description: Returned session
          content:
            application/json:
              schema:
                type: object
                $ref: ./effective-range-model.yaml#/components/schemas/Session
                x-stoplight:
                  id: mtflbe6ai8ijr
      operationId: get-session
      description: Get a shooting session by ID
      x-stoplight:
        id: 1uox80yjils10
  '/session/{id}/start':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Start session
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: start-session
      description: Start a shooting session
      x-stoplight:
        id: hcqcoebddojya
  '/session/{id}/end':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: End session
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: end-session
      description: End a shooting session
      x-stoplight:
        id: i0uio63eazv87
  '/session/{id}/pause':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Pause session
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: pause-session
      description: Pause a shooting session
      x-stoplight:
        id: qbdwidprddgfa
  '/session/{id}/resume':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Resume session
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: resume-session
      description: Resume a shooting session
      x-stoplight:
        id: zbaknxdu31w17
  '/session/{id}/rewind':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Rewind session
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: rewind-session
      description: Rewind a shooting session
      x-stoplight:
        id: 2q1l40xn0370v
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RewindSessionRequest'
  '/session/{id}/launch':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Manual launch
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: initiate-manual-launch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/ManualLaunchRequest'
      description: Initiate manual launch for a shooting session
      x-stoplight:
        id: ze72e0fgk0e0d
  '/session/{id}/event':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Trigger event
      tags:
        - session
      responses:
        '202':
          description: Accepted
      operationId: trigger-session-event
      x-stoplight:
        id: xdhdyp6s73adg
      description: Trigger a session event
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TriggerEventRequest'
components:
  schemas:
    CreateSessionRequest:
      title: CreateSessionRequest
      type: object
      required:
        - range_id
        - discipline_id
        - shooter_ids
      properties:
        range_id:
          type: string
          x-stoplight:
            id: aart5dimk9z5l
        discipline_id:
          type: string
          x-stoplight:
            id: 2rf02b3dse
        shooter_ids:
          x-stoplight:
            id: lkl3oq9ef4efj
          type: array
          items:
            x-stoplight:
              id: g2nle7t6sq5a7
            type: string
      x-stoplight:
        id: bep232hh076km
    TriggerEventRequest:
      title: TriggerEventRequest
      x-stoplight:
        id: jeinuka22jv99
      type: object
      required:
        - event_type
        - token
      properties:
        event_type:
          $ref: ./effective-range-model.yaml#/components/schemas/EventType
          x-stoplight:
            id: cjw1o4rn9cw13
        token:
          type: object
          $ref: ./effective-range-model.yaml#/components/schemas/Token
          x-stoplight:
            id: gftvtlg0p4iq9
    ManualLaunchRequest:
      title: ManualLaunchRequest
      type: object
      required:
        - machine_ids
      properties:
        machine_ids:
          type: array
          items:
            x-stoplight:
              id: mdoep5xdf3yuf
            type: string
      x-stoplight:
        id: oru90z9hqh0km
    RewindSessionRequest:
      title: RewindSessionRequest
      x-stoplight:
        id: rrhh2qxv4jwgn
      type: object
      required:
        - type
        - target
      properties:
        type:
          $ref: '#/components/schemas/RewindType'
          x-stoplight:
            id: wg3mx4e49mgom
        target:
          $ref: '#/components/schemas/RewindTarget'
          x-stoplight:
            id: 7v8cwiufmy0xy
    RewindType:
      title: RewindType
      x-stoplight:
        id: axhfr6sw79mo6
      enum:
        - turn
        - launch
    RewindTarget:
      title: RewindTarget
      x-stoplight:
        id: 9q9jesmra0ooi
      enum:
        - current
        - previous
