openapi: 3.1.0
x-stoplight:
  id: t7cn6d165fvem
info:
  version: 0.1.0
  title: Health API
  summary: Effective Range health API
  description: Component health API for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
tags:
  - name: health
    description: Component health
paths:
  /health/alive:
    post:
      summary: Signal component is alive
      tags:
        - health
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: w4ychh28buda2
      operationId: health-alive
      x-stoplight:
        id: oyvnyv2bljdwb
      description: Component signals it is alive on the network
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Component'
    parameters: []
  /health/status:
    post:
      summary: Signal component health status
      tags:
        - health
      responses:
        '202':
          description: Accepted
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                type: object
                $ref: ./model.yaml#/components/schemas/Error
                x-stoplight:
                  id: w4ychh28buda2
      operationId: health-status
      x-stoplight:
        id: fi4uqk45fkvij
      description: Component signals its health status
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Component'
    parameters: []
components:
  schemas:
    Component:
      title: Component
      x-stoplight:
        id: mnpauv0e7v27m
      type: object
      required:
        - id
        - uri
        - status_period
      properties:
        id:
          type: string
          x-stoplight:
            id: pdhfpm7q2wzxy
          format: uuid
        uri:
          type: string
          x-stoplight:
            id: l48ddk21l4ufp
          format: uri
        status_period:
          type: integer
          x-stoplight:
            id: pb7ux0wo2cydf
        session_id:
          type: string
          x-stoplight:
            id: 1ki5bqm69p8vx
          format: uuid
        error:
          type: object
          $ref: ./model.yaml#/components/schemas/Error
          x-stoplight:
            id: w4ychh28buda2
