openapi: 3.1.0
x-stoplight:
  id: wanywzlu3ptim
info:
  version: 0.1.0
  title: Common models
  summary: Effective Range common models
  description: Common models for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
tags:
  - name: common
    description: Common model
components:
  schemas:
    TriggerType:
      default: on_call
      enum:
        - on_call
        - on_shot
        - manual
      title: TriggerType
      type: string
      x-stoplight:
        id: mv4bimzewwjq6
      tags:
        - common
    Token:
      title: Token
      type: object
      x-stoplight:
        id: gftvtlg0p4iq9
      required:
        - id
        - type
        - expiry
      properties:
        id:
          format: uuid
          type: string
          x-stoplight:
            id: kkzh6ml6t612k
        type:
          $ref: '#/components/schemas/TriggerType'
          x-stoplight:
            id: mv4bimzewwjq6
        expiry:
          format: date-time
          type: string
          x-stoplight:
            id: 6lgq6ci9zojv3
        preceding:
          type: string
          x-stoplight:
            id: aolw5myc3blpf
          format: uuid
      tags:
        - common
