openapi: 3.1.0
x-stoplight:
  id: wanywzlu3ptim
info:
  version: 0.1.0
  title: Common models
  summary: Effective Range common models
  description: Common models for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
tags:
  - name: common
    description: Common model
paths: { }
components:
  schemas:
    TriggerType:
      default: on_call
      enum:
        - on_call
        - on_shot
        - manual
      title: TriggerType
      type: string
      x-stoplight:
        id: mv4bimzewwjq6
      tags:
        - common
    Token:
      title: Token
      type: object
      x-stoplight:
        id: gftvtlg0p4iq9
      tags:
        - common
      required:
        - id
        - trigger_type
      properties:
        id:
          format: uuid
          type: string
          x-stoplight:
            id: kkzh6ml6t612k
        pre_id:
          type: string
          x-stoplight:
            id: aolw5myc3blpf
          format: uuid
        trigger_type:
          $ref: '#/components/schemas/TriggerType'
          x-stoplight:
            id: mv4bimzewwjq6
    ErrorCode:
      title: ErrorCode
      x-stoplight:
        id: j2ov7zolqqaiv
      enum:
        - unknown
        - unreachable
        - status_expired
        - no_session
        - session_mismatch
        - invalid_token
        - invalid_argument
        - internal_error
        - local_error
        - invalid_state
      default: unknown
    Error:
      title: Error
      x-stoplight:
        id: is5kvrx25ljdf
      type: object
      required:
        - code
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
          x-stoplight:
            id: f72gwqw2t5nhe
        reason:
          type: string
          x-stoplight:
            id: a5zwe4rzhhpim
