openapi: 3.1.0
tags:
  - name: device
    description: Edge device
info:
  version: 0.1.0
  title: Device API
  summary: Effective Range device API
  description: Edge device related operations
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: www.effective-range.com
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
paths:
  /device:
    get:
      responses:
        '200':
          description: Returned devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: model.yaml#/components/schemas/Device
      operationId: get-devices
      summary: Get devices
      description: Get a list of all devices
      tags:
        - device
    parameters: []
    post:
      summary: Add device
      tags:
        - device
      responses:
        '201':
          description: Added
      operationId: add-device
      requestBody:
        content:
          application/json:
            schema:
              $ref: model.yaml#/components/schemas/Device
      description: Add a new device
  /device/active:
    get:
      responses:
        '200':
          description: Returned active devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: model.yaml#/components/schemas/Device
      operationId: get-active-devices
      summary: Get active devices
      description: Get a list of currently active devices
      tags:
        - device
    parameters: []
  '/device/{id}':
    get:
      responses:
        '200':
          description: Returned device
          content:
            application/json:
              schema:
                $ref: model.yaml#/components/schemas/Device
      operationId: get-device
      summary: Get device
      description: Get a device by ID
      tags:
        - device
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Device ID
