openapi: 3.1.0
tags:
  - name: device
    description: Edge device
  - name: discipline
    description: Shooting discipline
  - name: range
    description: Shooting range
  - name: session
    description: Shooting session
  - name: shooter
    description: Shooting competitor
info:
  version: 0.1.0
  title: Server API
  summary: Effective Range server API
  description: Backend server API for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
paths:
  /discipline:
    post:
      summary: Add discipline
      tags:
        - discipline
      responses:
        '201':
          description: Created
      operationId: add-discipline
      x-stoplight:
        id: a4qjcud5e3muc
      description: Add a clay shooting discipline
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Discipline'
    get:
      summary: Get disciplines
      tags:
        - discipline
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Discipline'
                  x-stoplight:
                    id: oesbgk7s2r9bw
      operationId: get-disciplines
      x-stoplight:
        id: r023imxkusoo8
      description: Get all clay shooting disciplines
  '/discipline/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Discipline ID
    get:
      summary: Get discipline
      tags:
        - discipline
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Discipline'
      operationId: get-discipline
      x-stoplight:
        id: t86q0egkjz12p
      description: Get a discipline by ID
      parameters: []
  /shooter:
    get:
      summary: Get shooters
      tags:
        - shooter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Shooter'
                  x-stoplight:
                    id: fmjf14fgqncp3
      operationId: get-shooters
      x-stoplight:
        id: 8019pvexup91b
      description: Get all shooter
    post:
      summary: Add shooter
      tags:
        - shooter
      responses:
        '201':
          description: Created
      operationId: add-shooter
      x-stoplight:
        id: tzsibxbelfecv
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Shooter'
      description: Add new shooter
  '/shooter/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Shooter ID
    get:
      summary: Get shooter
      tags:
        - shooter
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Shooter'
      operationId: get-shooter
      x-stoplight:
        id: 26nf97y2c8xq6
      description: Get shooter by ID
  /device:
    get:
      responses:
        '200':
          description: Returned devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
      operationId: get-devices
      summary: Get devices
      description: Get a list of all devices
      tags:
        - device
    parameters: []
    post:
      summary: Add device
      tags:
        - device
      responses:
        '201':
          description: Added
      operationId: add-device
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      description: Add a new device
  /device/active:
    get:
      responses:
        '200':
          description: Returned active devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
      operationId: get-active-devices
      summary: Get active devices
      description: Get a list of currently active devices
      tags:
        - device
    parameters: []
  '/device/{id}':
    get:
      responses:
        '200':
          description: Returned device
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
      operationId: get-device
      summary: Get device
      description: Get a device by ID
      tags:
        - device
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Device ID
  /range:
    get:
      summary: Get ranges
      tags:
        - range
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Range'
      operationId: get-ranges
      description: Get all shooting ranges
    post:
      summary: Add range
      tags:
        - range
      responses:
        '201':
          description: Added
      operationId: add-range
      description: Add a shooting range
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Range'
  '/range/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Range ID
    get:
      summary: Get range
      tags:
        - range
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Range'
      operationId: get-range
      description: Get a shooting range by ID
  '/range/{id}/session':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Range ID
    get:
      summary: Get active session
      tags:
        - range
        - session
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
      operationId: get-active-session
      description: Get the active shooting session on a shooting range
  /session:
    get:
      summary: Get sessions
      tags:
        - session
      responses:
        '200':
          description: Returned sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Session'
      operationId: get-sessions
      description: Get all shooting sessions
    post:
      operationId: create-session
      summary: Create session
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionRequest'
      tags:
        - session
      description: Create a new shooting session on a shooting range
  '/session/{id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    get:
      summary: Get session
      tags:
        - session
      responses:
        '200':
          description: Returned session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
      operationId: get-session
      description: Get a shooting session by ID
  '/session/{id}/start':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Start session
      tags:
        - session
      responses:
        '200':
          description: Started
          content: {}
      operationId: start-session
      description: Start a shooting session
  '/session/{id}/end':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: End session
      tags:
        - session
      responses:
        '200':
          description: Ended
      operationId: end-session
      description: End a shooting session
  '/session/{id}/pause':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Pause session
      tags:
        - session
      responses:
        '200':
          description: Paused
      operationId: pause-session
      description: Pause a shooting session
  '/session/{id}/resume':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Resume session
      tags:
        - session
      responses:
        '200':
          description: Resumed
      operationId: resume-session
      description: Resume a shooting session
  '/session/{id}/rewind':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Rewind session
      tags:
        - session
      responses:
        '200':
          description: Rewinded
      operationId: rewind-session
      description: Rewind a shooting session
  '/session/{id}/launch':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Manual launch
      tags:
        - session
      responses:
        '200':
          description: Rewinded
      operationId: initiate-manual-launch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualLaunchRequest'
      description: Initiate manual launch for a shooting session
  '/session/{id}/event':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Your POST endpoint
      tags:
        - session
      responses:
        '200':
          description: OK
      operationId: trigger-session-event
      x-stoplight:
        id: xdhdyp6s73adg
      description: Trigger a session event
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TriggerEventRequest'
components:
  schemas:
    Device:
      title: Device
      type: object
      required:
        - id
        - type
        - role
        - online
        - in_use
        - triggers
      properties:
        id:
          type: string
        type:
          type: string
          x-stoplight:
            id: g104uanwf6e9g
        role:
          type: string
        online:
          type: boolean
          x-stoplight:
            id: jacm9fmpjjiw1
        in_use:
          type: boolean
          x-stoplight:
            id: sv9jrp9ugffkl
        triggers:
          type: array
          x-stoplight:
            id: 3zwoczn21awr2
          items:
            $ref: '#/components/schemas/TriggerType'
            x-stoplight:
              id: ul95ms3kzx43g
    Range:
      title: Range
      type: object
      required:
        - id
        - station_map
        - machine_map
        - discipline_ids
      properties:
        id:
          type: string
          x-stoplight:
            id: 0ov8tifyfek3o
        station_map:
          type: object
          x-stoplight:
            id: ozhbuwpei1jj6
          additionalProperties:
            x-stoplight:
              id: v5jag1338km5e
            type: string
        machine_map:
          type: object
          x-stoplight:
            id: db5coooruyawv
          additionalProperties:
            x-stoplight:
              id: quiuz48zut16g
            type: string
        discipline_ids:
          type: array
          x-stoplight:
            id: ab7z2xlg423ks
          items:
            x-stoplight:
              id: dhoq4c46dh5sl
            type: string
    Shooter:
      title: Shooter
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
          x-stoplight:
            id: 57uhi42bwfcva
    Discipline:
      title: Discipline
      x-stoplight:
        id: cfx7mrbspij2o
      type: object
      required:
        - id
        - name
        - shooter_order
        - target_limit
        - turns
      properties:
        id:
          type: string
          x-stoplight:
            id: gikqrl1sxhvss
        name:
          type: string
          x-stoplight:
            id: eqogwyyqjfl2x
        shooter_order:
          $ref: '#/components/schemas/ShooterOrder'
          x-stoplight:
            id: yp1c3nul58q91
        target_limit:
          type: integer
          x-stoplight:
            id: scbb6b9swu8ec
          minimum: 1
          default: 25
        launch_delay:
          type: integer
          x-stoplight:
            id: mlw82lz284by5
          minimum: 0
          default: 0
        delay_type:
          $ref: '#/components/schemas/DelayType'
          x-stoplight:
            id: 617lmg3186txa
        option_bird:
          type: boolean
          x-stoplight:
            id: m07jgxznqngkd
          default: false
        turns:
          type: array
          x-stoplight:
            id: hzd80qhbrn7gt
          minItems: 1
          items:
            $ref: '#/components/schemas/TurnConfig'
            x-stoplight:
              id: wrr1cn7k6gyjl
    TurnConfig:
      title: TurnConfig
      x-stoplight:
        id: w9tza4t5cdgul
      type: object
      required:
        - station_ids
        - launches
      properties:
        station_ids:
          type: array
          x-stoplight:
            id: 99toevkner4rj
          minItems: 1
          items:
            x-stoplight:
              id: qs87p05dytoho
            type: string
        station_order:
          $ref: '#/components/schemas/StationOrder'
          x-stoplight:
            id: hx2ctv2ru53ng
        launches:
          type: array
          x-stoplight:
            id: plns501xqp2th
          minItems: 1
          items:
            $ref: '#/components/schemas/LaunchConfig'
            x-stoplight:
              id: qmqtmacalc2x5
    LaunchConfig:
      title: LaunchConfig
      x-stoplight:
        id: 7dy7smsffj66j
      type: object
      description: ''
      required:
        - machine_ids
      properties:
        machine_ids:
          type: array
          x-stoplight:
            id: e1ynjrxovj7po
          minItems: 1
          items:
            x-stoplight:
              id: gp1fmnfup0gaw
            type: string
        trigger_type:
          $ref: '#/components/schemas/TriggerType'
          x-stoplight:
            id: 482z99z9eyd4n
        machine_order:
          $ref: '#/components/schemas/MachineOrder'
          x-stoplight:
            id: keepmifbwehi9
        target_count:
          type: integer
          x-stoplight:
            id: typ5iras3n7oi
          minimum: 1
          default: 1
        condition_id:
          type: string
          x-stoplight:
            id: 89u80rwo0jwc9
    ShooterOrder:
      title: ShooterOrder
      x-stoplight:
        id: x6ebnxf7td1be
      enum:
        - sequential
        - rotational
      default: sequential
    DelayType:
      title: DelayType
      x-stoplight:
        id: b2gcrfade4f2k
      enum:
        - no_delay
        - fixed
        - random
      default: no_delay
    StationOrder:
      title: StationOrder
      x-stoplight:
        id: immjxsqpncmu2
      enum:
        - sequential
        - simultaneous
      default: sequential
    MachineOrder:
      title: MachineOrder
      x-stoplight:
        id: 6dcglqdba1vl0
      enum:
        - sequential
        - randomized
        - simultaneous
      default: sequential
    TriggerType:
      title: TriggerType
      x-stoplight:
        id: mv4bimzewwjq6
      enum:
        - on_call
        - on_shot
        - manual
      default: on_call
    Session:
      title: Session
      type: object
      required:
        - id
        - range
        - discipline
        - shooters
      properties:
        id:
          type: string
          format: uuid
        range:
          $ref: '#/components/schemas/Range'
        discipline:
          $ref: '#/components/schemas/Discipline'
          x-stoplight:
            id: ol4hpgadilpne
        shooters:
          type: array
          x-stoplight:
            id: s35m5h0hqxuqx
          items:
            $ref: '#/components/schemas/Shooter'
            x-stoplight:
              id: c0n7vjkxvps0d
    CreateSessionRequest:
      title: Create session
      type: object
      required:
        - range_id
        - discipline_id
        - shooter_ids
      properties:
        range_id:
          type: string
          x-stoplight:
            id: aart5dimk9z5l
        discipline_id:
          type: string
          x-stoplight:
            id: 2rf02b3dse
        shooter_ids:
          x-stoplight:
            id: lkl3oq9ef4efj
          type: array
          items:
            x-stoplight:
              id: g2nle7t6sq5a7
            type: string
    TriggerEventRequest:
      title: TriggerEventRequest
      x-stoplight:
        id: jeinuka22jv99
      type: object
      required:
        - event_id
        - event_type
      properties:
        event_id:
          type: string
          x-stoplight:
            id: t7cizbjp4cjxs
          format: uuid
        event_type:
          $ref: '#/components/schemas/EventType'
          x-stoplight:
            id: cjw1o4rn9cw13
    ManualLaunchRequest:
      title: Manual launch
      type: object
      required:
        - machine_ids
      properties:
        machine_ids:
          type: array
          items:
            x-stoplight:
              id: mdoep5xdf3yuf
            type: string
    EventType:
      title: EventType
      x-stoplight:
        id: elw9188rccbi7
      enum:
        - CallTarget
        - TakeShot
        - LaunchTarget
