openapi: 3.1.0
tags:
  - name: model
    description: Common models
info:
  version: 0.1.0
  title: Effective Range API models
  summary: Effective Range core API models
  description: Common models to be used by core APIs
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: www.effective-range.com
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
components:
  schemas:
    Device:
      title: Device
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          x-stoplight:
            id: g104uanwf6e9g
        role:
          type: string
        active:
          type: boolean
        in_use:
          type: boolean
          x-stoplight:
            id: sv9jrp9ugffkl
    Range:
      title: Range
      type: object
      properties:
        id:
          type: string
        devices:
          type: array
          x-stoplight:
            id: xubasdthzxrgr
          items:
            $ref: '#/components/schemas/Device'
        disciplines:
          type: array
          x-stoplight:
            id: n1fdieap3rn6u
          items:
            x-stoplight:
              id: iwnlxyoq3sf0g
            type: string
    Shooter:
      title: Shooter
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          x-stoplight:
            id: 57uhi42bwfcva
    Session:
      title: Session
      type: object
      properties:
        id:
          type: string
          format: uuid
        range:
          $ref: '#/components/schemas/Range'
        discipline:
          type: string
          x-stoplight:
            id: ol4hpgadilpne
        shooters:
          type: array
          x-stoplight:
            id: s35m5h0hqxuqx
          items:
            $ref: '#/components/schemas/Shooter'