openapi: 3.1.0
tags:
  - name: session
    description: Shooting session
info:
  version: 0.1.0
  title: Session API
  summary: Effective Range session API
  description: Shooting session related operations
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: www.effective-range.com
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
paths:
  /session:
    get:
      summary: Get sessions
      tags:
        - session
      responses:
        '200':
          description: Returned sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: model.yaml#/components/schemas/Session
      operationId: get-sessions
      description: Get all shooting sessions
    post:
      operationId: create-session
      summary: Create session
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    x-stoplight:
                      id: eno6idn0cpg3y
                    format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSession'
      tags:
        - session
      description: Create a new shooting session on a shooting range
  '/session/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    get:
      summary: Get session
      tags:
        - session
      responses:
        '200':
          description: Returned session
          content:
            application/json:
              schema:
                $ref: model.yaml#/components/schemas/Session
      operationId: get-session
      description: Get a shooting session by ID
  '/session/{id}/start':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Start session
      tags:
        - session
      responses:
        '200':
          description: Started
          content: {}
      operationId: start-session
      description: Start a shooting session
  '/session/{id}/end':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: End session
      tags:
        - session
      responses:
        '200':
          description: Ended
      operationId: end-session
      description: End a shooting session
  '/session/{id}/pause':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Pause session
      tags:
        - session
      responses:
        '200':
          description: Paused
      operationId: pause-session
      description: Pause a shooting session
  '/session/{id}/resume':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Resume session
      tags:
        - session
      responses:
        '200':
          description: Resumed
      operationId: resume-session
      description: Resume a shooting session
  '/session/{id}/rewind':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Rewind session
      tags:
        - session
      responses:
        '200':
          description: Rewinded
      operationId: rewind-session
      description: Rewind a shooting session
  '/session/{id}/launch':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Session ID
    post:
      summary: Manual launch
      tags:
        - session
      responses:
        '200':
          description: Rewinded
      operationId: manual-launch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualLaunch'
      description: Initiate manual launch for a shooting session
components:
  schemas:
    CreateSession:
      title: Create session
      type: object
      properties:
        range_id:
          type: string
          x-stoplight:
            id: aart5dimk9z5l
        discipline_id:
          type: string
          x-stoplight:
            id: 2rf02b3dsb0ay
        device_order:
          type: array
          x-stoplight:
            id: 45b1jdynag16o
          items:
            x-stoplight:
              id: s3wwn2nujdwf9
            type: string
        shooter_order:
          x-stoplight:
            id: lkl3oq9ef4efj
          type: array
          items:
            x-stoplight:
              id: g2nle7t6sq5a7
            type: string
    ManualLaunch:
      title: Manual launch
      type: object
      properties:
        devices:
          type: array
          items:
            x-stoplight:
              id: mdoep5xdf3yuf
            type: string
