@startuml

hide empty description

header Effective Range device
title Device state machine

[*] --> NotConnected
NotConnected --> Connected : ServerAlive
Connected --> NotConnected : StatusExpired

Connected --> InSession : StartSession
InSession --> Connected : EndSession

InSession --> ActiveWithTokens : Activate
ActiveWithTokens --> ActiveWithTokens : ReportEvent
ActiveWithTokens --> ActiveWithoutTokens : ReportEvent
ActiveWithoutTokens --> InSession : Deactivate

footer Effective Range device

@enduml
