@startuml
hide empty description

header Effective Range server
title Session state machine

[*] --> SessionCreated
SessionCreated --> SessionStarted : StartSession/ReserveRange
SessionStarted --> TurnStarted
TurnStarted : entry/LogTurnInfo
TurnStarted --> LaunchStarted

LaunchStarted : entry/LogLaunchInfo
LaunchStarted : entry/ActivateDevices
LaunchStarted --> LaunchActivated : ActivateLaunch

state LaunchActivatedChoice <<choice>>

' Successful launch
LaunchActivated --> LaunchActivatedChoice : ReportEvent\n/ProcessEvent
LaunchActivatedChoice --> LaunchActivated : [IsLaunchIncomplete]
LaunchActivatedChoice --> LaunchCompleted : [IsLaunchComplete]
LaunchCompleted : entry/DeactivateDevices

state LaunchCompleteChoice <<choice>>

LaunchCompleted --> LaunchCompleteChoice
LaunchCompleteChoice --> LaunchStarted : [IsTurnIncomplete]\n/NextLaunch
LaunchCompleteChoice --> TurnEnded : [IsTurnComplete]

LaunchActivated --> LaunchDeactivated : CancelLaunch/InterruptActivation
LaunchDeactivated : entry/DeactivateDevices
LaunchDeactivated --> SessionEnded : EndSession/ReleaseRange

' Restart launch
LaunchDeactivated --> LaunchStarted : RestartLaunch

' Failed launch
LaunchStarted --> LaunchFailed : SignalFailure
LaunchActivated --> LaunchFailed : SignalFailure
LaunchCompleted --> LaunchFailed : SignalFailure
LaunchDeactivated --> LaunchFailed : SignalFailure
LaunchFailed --> LaunchStarted : ResetSession/ResetRange
LaunchFailed --> SessionEnded : EndSession/ReleaseRange

' Continue session after server restart
LaunchActivated --> LaunchStarted : ResetSession/ResetRange

' Rewound session
state SessionRewoundChoice <<choice>>

LaunchDeactivated --> SessionRewound : RewindSession
SessionRewound --> SessionRewoundChoice
SessionRewoundChoice --> LaunchStarted : [IsRewindLaunch]\n/RewindLaunch
SessionRewoundChoice --> TurnStarted : [IsRewindTurn]\n/RewindTurn

state TurnEndedChoice <<choice>>

TurnEnded --> TurnEndedChoice
TurnEndedChoice --> TurnStarted : [IsSessionIncomplete]\n/NextTurn
TurnEndedChoice --> SessionCompleted : [IsSessionComplete]
SessionCompleted --> SessionRewound : RewindSession
SessionCompleted --> SessionEnded : EndSession/ReleaseRange
SessionEnded --> [*]

footer Effective Range server

@enduml
