openapi: 3.1.0
info:
  version: 0.1.0
  title: Device API
  summary: Effective Range device API
  description: Edge device API for the Effective Range system
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: 'https://www.effective-range.com'
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
tags:
  - name: device
    description: Edge device
paths:
  /device/activate:
    get:
      summary: Activate device
      tags:
        - device
      responses:
        '202':
          description: Accepted
      operationId: activate-device
      x-stoplight:
        id: aq16emkx2iucl
      description: Activate device for launch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Token'
    parameters: []
  /device/deactivate:
    get:
      summary: Deactivate device
      tags:
        - device
      responses:
        '202':
          description: Accepted
      operationId: deactivate-device
      x-stoplight:
        id: 5qetcgo65ggdi
      description: Deactivate device for launch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Token'
    parameters: []
components:
  schemas:
    TriggerType:
      title: TriggerType
      x-stoplight:
        id: mv4bimzewwjq6
      enum:
        - on_call
        - on_shot
        - manual
      default: on_call
    Token:
      title: Token
      x-stoplight:
        id: gftvtlg0p4iq9
      type: object
      required:
        - id
        - type
        - expiry
      properties:
        id:
          type: string
          x-stoplight:
            id: kkzh6ml6t612k
          format: uuid
        type:
          $ref: '#/components/schemas/TriggerType'
          x-stoplight:
            id: p6bwyzmi74ffo
        expiry:
          type: string
          x-stoplight:
            id: 6lgq6ci9zojv3
          format: date-time
