openapi: 3.1.0
info:
  version: 0.1.0
  title: Firing station API
  description: Effective Range firing station API
  contact:
    name: Effective Range
    email: info@effective-range.com
    url: www.effective-range.com
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/EffectiveRange/effective-range-api/refs/heads/main/LICENSE'
